apiVersion: v1
kind: Secret
metadata:
  name: example-provider-secret
type: Opaque
data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: ytt.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
